.

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -58,6 +58,19 @@ pipeline {
             }
         }
 
+        stage('Debug Workspace') {
+            steps {
+                sh '''
+                echo "--- WORKSPACE CONTENTS ---"
+                pwd
+                ls -R .
+                echo "--- Check prometheus.yml ---"
+                ls -l ./prometheus/prometheus.yml || echo "FILE NOT FOUND"
+                '''
+            }
+        }
+
+
         stage('Deploy with Docker Compose') {
             steps {
                 script { notifyDiscord(":whale: Starting Docker Compose deployment...") }
